import Head from 'next/head';
import Image from 'next/image';
import stylesHome from '../styles/Home.module.scss';
import text from '../utils/textContent.json';

export default function Home() {
  
  return (
    <div className={`container`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <title>ATHENA EQUINE AS</title>
      </Head>
      <div className={stylesHome.home}>
        <div className={stylesHome.companyPicture}>
          <img src="https://image.freepik.com/free-photo/family-celebrating-festive-christmas-dinner_23-2149145005.jpg" />
        </div>
        <h3 className={stylesHome.companyMotto}>{text.eng.home.companyMotto}</h3>
        <div className={stylesHome.companyDescription}>
            <p>{text.eng.home.companyDescription.p1}</p>
            <p>{text.eng.home.companyDescription.p2}</p>
            <p>{text.eng.home.companyDescription.p3}</p>
        </div>
        <div className={`row ${stylesHome.employees}`}>
            <div className={`${stylesHome.employee}`}>
                <h4 className={stylesHome.employeeName}>Elisabeth Hernes</h4>
                <div className={stylesHome.employeePhotoContainer}>
                  <img src="/ELISABETH.jpg" alt="Elisabeth"/>
                </div>
                <p className={stylesHome.employeeDescription}>{text.eng.home.employeeDescription.elizabeth}</p>
            </div>
            <div className={`${stylesHome.employee}`}>
                <h4 className={stylesHome.employeeName}>Kamila Derewianska</h4>
                <div className={stylesHome.employeePhotoContainer}>
                  <img src="/KAMILA.jpg" alt="Kamila"/>
                </div>
                <p className={stylesHome.employeeDescription}>{text.eng.home.employeeDescription.kamila}</p>
            </div>
            <div className={`${stylesHome.employee}`}>
                <h4 className={stylesHome.employeeName}>Ida Louise Vordtvedt</h4>
                <div className={stylesHome.employeePhotoContainer}>
                  <img src="/IDA.jpg" alt="Ida"/>
                </div>
                <p className={stylesHome.employeeDescription}>{text.eng.home.employeeDescription.ida}</p>
            </div>
            <div className={`${stylesHome.employee}`}>
                <h4 className={stylesHome.employeeName}>Anine Aarum Teig</h4>
                <div className={stylesHome.employeePhotoContainer}>
                  <img src="/ANINE.jpeg" alt="Anine"/>
                </div>
                <p className={stylesHome.employeeDescription}>{text.eng.home.employeeDescription.anine}</p>
            </div>
        </div>
        <div className={stylesHome.companyDescription}>
            <p>{text.eng.home.companyDescription.p4}</p>
        </div>
      </div>
    </div>
  )
}

